# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d14c26e8f2ec08baccb4e5cd23d53f0bb220266526eb1101b06a3fba0c5d7198f9a9d8cf321ee8f7076f7524b68e9a107ac4f829ea8a4dd3c5c6419b9c8262f

test:
  secret_key_base: a410b2d622ac6c9960c5efe0d98e82221dc86d2eb4845d72ab37956ddf780666dffc0138ca49c757a33fad16e1c2d65ea24c6e5acf2fb58d9776201c6dea80ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
