version: '2'

services:
  redis:
    image: redis:latest

  sidekiq:
    depends_on:
      - redis
    build: ./rails_app
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0

  rails_app:
    build: ./rails_app
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  phoenix_app:
    build: ./phoenix_app
    ports:
      - 4000:4000
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
